openpecha-editor-old-master/editor/main/__init__.py
from . import views

openpecha-editor-old-master/editor/main/views.py
import time

import requests
from flask import (
    Blueprint,
    flash,
    jsonify,
    redirect,
    render_template,
    request,
    session,
    url_for,
)

from editor.extensions import github_oauth
from editor.user.models import RoleType, User
from editor.utils import (
    create_export,
    create_export_issue,
    create_issue,
    get_opf_layers_and_formats,
)

blueprint = Blueprint("main", __name__, url_prefix="/", static_folder="../static")


@blueprint.route("/")
def index():
    return render_template("index.html")


@blueprint.route("/<pecha_id>")
def editor(pecha_id):
    # login or register to github account
    if "user_id" not in session:
        if "user_id" in session:
            return redirect(url_for("main.editor", pecha_id=pecha_id))
        session["next_url"] = url_for("main.editor", pecha_id=pecha_id)
        return render_template("login.html")

    # Register user to text repo if not
    user = User.query.get(session["user_id"])
    if not user.pecha_id:
        return render_template("register.html", pecha_id=pecha_id)

    is_owner = False
    if user.role == RoleType.owner:
        is_owner = True
    layers, formats = get_opf_layers_and_formats(pecha_id)
    return render_template(
        "main.html",
        pecha_id=pecha_id,
        layers=layers,
        formats=formats,
        is_owner=is_owner,
    )


@blueprint.route("/export", methods=["POST"])
def export():
    # Get layers and format
    pecha_id = request.args.get("pecha_id")
    layers = request.form.getlist("layers")
    format_ = request.form.getlist("format")

    # Create github issue
    asset_download_url = create_export(
        pecha_id, layers, format_[0], session.get("user_access_token")
    )

    if asset_download_url:
        return render_template("download_page.html", download_url=asset_download_url)
        # flash( #     f"{pecha_id} is being exported. Please go to Download section to download the file", #     "info", # )
    else:
        flash(f"{pecha_id} cloud not be exported. Please try again later", "danger")
        return redirect(url_for("main.index", pecha_id=pecha_id))


@blueprint.route("/publish")
def publish():
    pecha_id = request.args.get("pecha_id")

    # Login with Github
    if session.get("user_id", None) is None:
        session["next_url"] = url_for("main.publish", pecha_id=pecha_id)
        return github_oauth.authorize()

    user = User.query.get(session["user_id"])
    if user.role == RoleType.owner:
        issue_title = "Update OPF"
        issue_body = "create publish"
        issue = create_issue(pecha_id, issue_title, body=issue_body, labels=["publish"])

        if issue:
            flash(
                f"{pecha_id} is being updated. This may take a few minutes", "success"
            )
        else:
            flash(
                f"{pecha_id} cloud not be updated at the moment. Please try again later",
                "danger",
            )
    else:
        flash("Only owner can update the pecha", "danger")

    return redirect(url_for("main.index", pecha_id=pecha_id))


@blueprint.route("/download/<org>/<pecha_export_fn>")
def download(org, pecha_export_fn):
    download_api_url = url_for(
        "main.download_api", org=org, pecha_export_fn=pecha_export_fn, _external=True
    )
    print(download_api_url)
    r = requests.get(download_api_url)
    return redirect(r.json()["download_url"])


# ~~~~~~ API ~~~~~~~


@blueprint.route("/api/download/<org>/<pecha_export_fn>")
def download_api(org, pecha_export_fn):
    pecha_id, format_ = pecha_export_fn.split(".")
    json_response = {
        "pecha_id": pecha_id,
        "export_format": format_,
        "download_url": f"https://github.com/{org}/{pecha_id}/releases/latest/download/{pecha_export_fn}",
    }
    is_export_issue_created = False
    while True:
        r = requests.get(json_response["download_url"])
        if r.status_code == 200:
            return jsonify(json_response)
        else:
            if not is_export_issue_created:
                create_export_issue(pecha_id, format_=f".{format_}")
                is_export_issue_created = True
            time.sleep(5)

openpecha-editor-old-master/editor/pecha/views.py
from pathlib import Path
from uuid import uuid4

from flask import Blueprint, abort, current_app, redirect, request, url_for
from openpecha.catalog import CatalogManager
from openpecha.formatters import HFMLFormatter

from .models import Pecha

blueprint = Blueprint("pecha", __name__, url_prefix="/pecha", static_folder="../static")


def validate_img_extension(fn):
    fn = Path(fn)
    if fn.suffix not in current_app.config["UPLOAD_EXTENSIONS"]:
        abort(400)
    return fn.name


def save_image(parents_dir, file_obj):
    filename = validate_img_extension(file_obj.filename)
    base_dir = current_app.config["BOOK_ASSETS_UPLOAD_PATH"] / parents_dir
    base_dir.mkdir(exist_ok=True, parents=True)
    file_path = base_dir / filename
    file_obj.save(file_path)
    return filename


def parser_authors(string):
    delimeter = " "
    if "," in string:
        delimeter = ","
    return [author.strip() for author in string.split(delimeter)]


def create_soruce_metadata(request):
    title = request.form.get("title")
    subtitle = request.form.get("sub-title")
    authors = request.form.get("author")
    collection_title = request.form.get("collection-title")
    publisher = request.form.get("publisher")
    id_ = request.form.get("sku")
    front_cover_image = request.files.get("front-cover-image")
    publication_data_image = request.files.get("publication-data-image")
    content_images = request.files.getlist("content-images")

    # save images
    assets_path = "assets/images"
    pecha_images_path = f"{id_}/{assets_path}"
    pecha_content_images_path = f"{pecha_images_path}/content"
    front_cover_image_fn = save_image(pecha_images_path, front_cover_image)
    publication_data_image_fn = save_image(pecha_images_path, publication_data_image)
    for content_image in content_images:
        save_image(pecha_content_images_path, content_image)

    metadata = {
        "id": id_.strip(),
        "title": title.strip(),
        "subtitle": subtitle.strip(),
        "author": authors,
        "collection-title": collection_title.strip(),
        "publisher": publisher.strip(),
        "images": {
            "front-cover-image": f"{assets_path}/{front_cover_image_fn}",
            "publication-data-image": f"{assets_path}/{publication_data_image_fn}",
            "content-images-path": f"{assets_path}/content",
        },
    }

    return metadata


def save_text(parents_dir, text):
    base_dir = current_app.config["BOOK_ASSETS_UPLOAD_PATH"] / parents_dir
    base_dir.mkdir(exist_ok=True, parents=True)
    text_fn = base_dir / "v001.txt"
    text_fn.write_text(text)
    return text_fn.parent


@blueprint.route("/create", methods=["POST"])
def create_pecha():
    source_metadata = create_soruce_metadata(request)
    text_path = save_text(
        f"{source_metadata['id']}/text", request.form.get("content-text")
    )
    layers = [
        "book-title",
        "chapter-title",
        "author",
        "cition",
        "sabche",
        "root-verse",
        "foot-note",
        "all",
    ]
    catalog = CatalogManager(
        formatter=HFMLFormatter(
            metadata={"source_metadata": source_metadata, "layers": layers}
        ),
        layers=layers,
        token=current_app.config["GITHUB_TOKEN"],
    )
    catalog.add_hfml_item(text_path)
    catalog.update()
    pecha_id = f"P{catalog.last_id:06}"
    return redirect(url_for("main.editor", pecha_id=pecha_id))


@blueprint.route("/secret", methods=["POST"])
def create_secret():
    for i in range(100, 101):
        pecha_id = f"P{i:06}"
        pecha = Pecha.query.filter_by(id=pecha_id).first()
        if pecha:
            continue
        Pecha.create(id=pecha_id, secret_key=uuid4().hex)
        print(f"added {pecha_id}")
    return redirect(url_for("user.admin_dashboard"))

    # pecha_id = request.form.get("pecha-id")
    # if pecha_id and not pecha_id.startswith(PECHA_PREFIX):
    #     flash(f"{pecha_id} is in valid", "danger")
    # pecha = Pecha.create(id=pecha_id, secret_key=uuid4().hex)
    # if pecha:
    #     flash(f"Secret Key successfully created for {pecha.id}", "success")

openpecha-editor-old-master/editor/user/views.py
from flask import (
    Blueprint,
    current_app,
    flash,
    jsonify,
    redirect,
    render_template,
    request,
    session,
    url_for,
)

from editor.extensions import github_oauth
from editor.pecha.form import PechaSecretKeyForm
from editor.pecha.models import Pecha

from .models import RoleType, User

blueprint = Blueprint("user", __name__, url_prefix="/users", static_folder="../static")


@github_oauth.access_token_getter
def token_getter():
    return session.get("user_access_token", None)


@blueprint.route("/github-callback")
@github_oauth.authorized_handler
def authorized(access_token):
    next_url = session.get("next_url")
    if access_token is None:
        flash("Authorization failed.", category="error")
        return redirect(next_url)
    session["user_access_token"] = access_token
    github_user = github_oauth.get("/user")
    user = User.query.filter_by(username=github_user["login"]).first()

    # add user to database
    if user is None:
        user = User.create(username=github_user["login"])
        # add admin user
        if not user.role and user.username in current_app.config["OP_ADMIN_USERS"]:
            user.update(role=RoleType.admin)

    session["user_id"] = user.id
    return redirect(next_url)


@blueprint.route("/login")
def login():
    return github_oauth.authorize()


@blueprint.route("/logout")
def logout():
    pecha_id = request.args.get("pecha_id")
    branch = request.args.get("branch")
    session.pop("user_id", None)
    return redirect(url_for("main.index", pecha_id=pecha_id, branch=branch))


@blueprint.route("/validate-secret", methods=["GET", "POST"])
def validate_secret_key():
    pecha_id = request.args.get("pecha_id")
    form = PechaSecretKeyForm()
    if request.method != "POST":
        context = {
            "title": "Secret Key",
            "form": form,
            "pecha_id": pecha_id,
            "is_owner": False,
        }
        return render_template("secret_key_form.html", **context)

    if form.validate_on_submit():
        secret_key = form.secret_key.data
        if len(secret_key) == 32:
            pecha = Pecha.query.filter_by(secret_key=secret_key).first()
            if pecha:
                return redirect(
                    url_for("user.register_user", pecha_id=pecha.id, is_owner=True)
                )
        flash("Invalid Pecha Secret Key!", "danger")
        return redirect(url_for("main.index", pecha_id=pecha_id))


@blueprint.route("/register-user", methods=["GET", "POST"])
def register_user():
    pecha_id = request.args.get("pecha_id")
    is_owner = request.args.get("is_owner")

    # Update pecha-id and role of the user
    user = User.query.get(session["user_id"])
    if is_owner == "True":
        user.update(role=RoleType.owner)
    else:
        user.update(role=RoleType.contributor)
    user.update(pecha_id=pecha_id)
    send_invitation(user, pecha_id)

    return redirect(url_for("main.editor", pecha_id=pecha_id))


def send_invitation(user, pecha_id):
    add_collaborator_url = f"https://api.github.com/repos/OpenPecha/{pecha_id}/collaborators/{user.username}"
    headers = {"Authorization": f"token {current_app.config['GITHUB_TOKEN']}"}
    res = github_oauth.session.request("PUT", add_collaborator_url, headers=headers)
    if res.status_code == 201:
        flash(
            f"Please check your Github linked Email to complete the Registration to {pecha_id}",
            "info",
        )
    elif res.status_code == 204:
        flash(f"User already registered to {pecha_id}", "info")
    else:
        flash("Registration failed. Please try again later", "danger")


@blueprint.route("/admin")
def admin_dashboard():
    if session.get("user_id", None) is None:
        session["next_url"] = url_for("user.admin_dashboard")
        return render_template("login.html")

    user = User.query.get(session["user_id"])
    if user.username not in current_app.config["OP_ADMIN_USERS"]:
        return "You don't have access to this page"

    pechas = Pecha.query.all()
    users = User.query.all()
    return render_template(
        "admin_page.html", title="Admin Page", pechas=pechas, users=users
    )


# ~~~~~~ API ~~~~~~~


@blueprint.route("/api/auth")
def auth():
    if "user_id" in session:
        user = User.query.get(session["user_id"])
        if user:
            result = {"status": 200, "token": session["user_access_token"]}
        else:
            result = {"status": 404, "message": "User not registered."}
    else:
        result = {
            "status": 404,
            "message": "User not logged in. Please login to openpecha editor",
        }
    return jsonify(result)

openpecha-editor-old-master/editor/templates/admin_page.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <h1>{{ title }}</h1>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    <button class="btn btn-primary" data-toggle="modal" data-target="#PechaSecretModal">Add Pecha</button>
    <h3> Pechas </h3>
    <table class="table">
        <thead class="thead-dark">
            <th scope="col">Pecha Id</th>
            <th scope="col">Secret Key</th>
        </thead>
        <tbody>
            {% for pecha in pechas %}
            <tr>
                <th scopr="row">{{ pecha.id }}</th>
                <td>{{ pecha.secret_key }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <h3> Users </h3>
    <table class="table">
        <thead class="thead-dark">
            <th scope="col">Username</th>
            <th scope="col">Pecha ID</th>
            <th scope="col">Role</th>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <th scopr="row">{{ user.username }}</th>
                <td>{{ user.pecha_id }}</td>
                <td>{{ user.role.value }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <!-- Export Modal -->
    <div class="modal fade" id="PechaSecretModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Enter Pecha ID</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ url_for('pecha.create_secret') }}" method="post">
                        <fieldset class="form-group">
                            <input type="text" class="form-control" name="pecha-id">
                        </fieldset>
                        <button type="submit" class="btn btn-sm btn-outline-success btn-block">Create</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

openpecha-editor-old-master/editor/templates/download_page.html
{% extends "login_layout.html" %}

{% block title %}OpenPecha | Download {% endblock %}

{% block form_content %}
<div class="login-form-container">
    <a href="{{ download_url }}" class="btn btn-success" tagert="_blank">Download</a>
</div>
{% endblock %}

openpecha-editor-old-master/editor/templates/layout.html
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='img/icons/book.png') }}" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">

    {% block head %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    {% block nav %}{% endblock %}

    <!-- <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
    </div> -->
    <div class="loader" style="display: none;">
        <img src="{{ url_for('static', filename='img/loading.svg') }}" alt="Loading..." />
    </div>
    {% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

openpecha-editor-old-master/editor/templates/login.html
{% extends "login_layout.html" %}

{% block title %}OpenPecha | Login{% endblock %}

{%block form_content %}
<form class="login-form-container">
  <div class="form-group">
    <center>
      <p>Welcome to Openpecha Editor</p>
    </center>
  </div>
  <a href="{{ url_for('user.login') }}" class="btn btn-primary btn-block">Login/Register</a>
</form>
{% endblock %}

openpecha-editor-old-master/editor/templates/login_layout.html
{% extends "layout.html" %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
{% endblock %}

{% block content %}
<div class="container-fluid bg">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-6 col-md-3">
      {% block form_content %}{% endblock %}
      </form>
    </div>
  </div>
</div>
{% endblock %}

openpecha-editor-old-master/editor/templates/main.html
{% extends "layout.html" %}
{% block head %}
<!--Fonts-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/font.css') }}">

<!-- CodeMirror -->
<script src="{{ url_for('static', filename='codemirror/lib/codemirror.js') }}"></script>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='codemirror/lib/codemirror.css') }}">

<!-- CodeMirror theme -->
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='codemirror/theme/darcula.css') }}">

<!-- CodeMirror mode -->
<script src="{{ url_for('static', filename='codemirror/addon/mode/simple.js') }}"></script>
<script src="{{ url_for('static', filename='codemirror/mode/hfml/hfml.js') }}"></script>

<!-- CodeMirror adons -->
<link rel="stylesheet" type="text/css"
    href="{{ url_for('static', filename='codemirror/addon/display/fullscreen.css') }}">
<script src="{{ url_for('static', filename='codemirror/addon/display/fullscreen.js') }}"></script>

<!-- Custome CSS -->
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/toolbar.css') }}">

{% endblock %}

{% block title %}OpenPecha | Editor{% endblock %}

{% block nav %}
<div class="toolbar">

    <div class="toolbar-item item-left">
        <a href="#" data-toggle="collapse" data-target="#demo" id="files-toggle"><img
                src="{{ url_for('static', filename='img/icons/book.png') }}" alt="book-icon"
                style="height: 25px; width: 25px;"></a>
    </div>
    <div class="item-left delimeter"></div>
    <div class="toolbar-item item-left">
        <div class="btn-group">
            <span>Layers:</span>
            <button id="cur-ann-label" class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="true"></button>
            <ul class="dropdown-menu">
                <h6 class="dropdown-header">VIEWS</h6>
                <li class="dropdown-submenu">
                    <a class="dropdown-item" href="#">Tsadra Epub</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">BookTitle</a></li>
                        <li><a class="dropdown-item" href="#">Author</a></li>
                        <li><a class="dropdown-item" href="#">Chapter</a></li>
                        <li><a class="dropdown-item" href="#">Citation</a></li>
                        <li><a class="dropdown-item" href="#">Sabche</a></li>
                        <li><a class="dropdown-item" href="#">BaseText</a></li>
                    </ul>
                </li>
                <li class="dropdown-submenu">
                    <a class="dropdown-item" href="#">Diplomatic Edition</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Normalization</a></li>
                    </ul>
                </li>
                <div class="dropdown-divider"></div>
                <h6 class="dropdown-header">ANNOTATIONS</h6>
                <li><a class="dropdown-item" href="#">BookTitle</a></li>
                <li><a class="dropdown-item" href="#">Author</a></li>
                <li><a class="dropdown-item" href="#">Chapter</a></li>
                <li><a class="dropdown-item" href="#">Citation</a></li>
                <li><a class="dropdown-item" href="#">Sabche</a></li>
                <li><a class="dropdown-item" href="#">BaseText</a></li>
                <li><a class="dropdown-item" href="#">publication</a></li>
            </ul>
        </div>
    </div>
    <!-- <div class="item-left delimeter"></div>
    <div class="toolbar-item item-left">
        <span class="toolbar-legend">Theme</span>
        <select onchange="selectTheme()" class="selector">
            <option selected>default</option>
            <option>3024-day</option>
            <option>3024-night</option>
            <option>abcdef</option>
            <option>ambiance</option>
            eoptioneayu-dark</option>
        </select>
    </div> -->
    <div class="item-left delimeter"></div>
    <div class="toolbar-item item-left">
        <a href="#" data-toggle="modal" data-target="#exportModal"><img
                style="height: 18px; width: 18px; margin-top: 2px;"
                src="{{ url_for('static', filename='img/icons/download.png') }}" alt="upload-icon"></a>
    </div>
    {% if is_owner %}
    <div class="item-left delimeter"></div>
    <div class="toolbar-item item-left">
        <a id="publish-link" href="{{ url_for('main.publish', pecha_id=pecha_id) }}"><span
                class="toolbar-button">Publish</span></a>
    </div>
    {% endif %}

    <div class="toolbar-item item-right">
        <a id=href="{{ url_for('user.logout', pecha_id=pecha_id) }}"><span class="toolbar-button">Logout<img
                    id="hunCaret" src="" alt=""></span></a>
    </div>

    <div class="toolbar-item item-right">
        <a href="#"><span id="upload"><img style="height: 20px; width: 20px;"
                    src="{{ url_for('static', filename='img/icons/upload.png')}}" alt="upload-icon"></a>
        </span></a>
    </div>

</div>
{% endblock %}

{% block content %}


<!-- Export Modal -->
<div class="modal fade" id="exportModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Download</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ url_for('main.export', pecha_id=pecha_id) }}" method="post">
                    <fieldset class="form-group">
                        <b>Choose Annotations</b>
                        {% for layer in layers %}
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" name="layers" value="{{ layer }}">
                            <label class="form-check-label">
                                <i>{{ layer }}</i>
                            </label>
                        </div>
                        {% endfor %}
                        <b>Choose Format:</b>
                        {% for format in formats %}
                        <div class="form-check">
                            <input type="radio" class="form-check-input" name="format" value="{{ format }}">
                            <label class="form-check-label">
                                <i>{{ format }}</i>
                            </label>
                        </div>
                        {% endfor %}
                    </fieldset>
                    <button type="submit" class="btn btn-sm btn-outline-success btn-block">Download</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row main">
    <div class="col-1 scrollbar collapse" id="demo">
        <div class="repo-files" id="file-list"></div>
    </div>
    <div class="col" id="editor-section">
        <div class="container" id="editor"></div>
    </div>
</div>

<script type="module" src="{{ url_for('static', filename='js/utils.js') }}"></script>
<script type="module" src="{{ url_for('static', filename='js/github.js') }}"></script>
<script type="module" src="{{ url_for('static', filename='js/files.js') }}"></script>
<script type="module">
    import { listFiles } from "{{ url_for('static', filename='js/files.js') }}";

    function updateAnnLabel(annName) {
        $('#cur-ann-label').html(annName + ' <span class="caret"></span>');
    }

    $(document).ready(function () {
        $(".dropdown-menu li a").click(function () {
            var annName = $(this).text();
            updateAnnLabel(annName);
            listFiles('OpenPecha', '{{ pecha_id }}', annName);
        });

        //preload BaseText
        var defaultAnnName = "BaseText";
        updateAnnLabel(defaultAnnName);
        listFiles('OpenPecha', '{{ pecha_id }}', defaultAnnName);

    });
</script>
<script type="module" src="{{ url_for('static', filename='js/editor.js') }}"></script>
{% endblock %}

openpecha-editor-old-master/editor/templates/register.html
{% extends "login_layout.html" %}

{% block title %}OpenPecha | Register{% endblock %}

{%block form_content %}
<form class="login-form-container">
    <center>
        <p>Register as</p>
    </center>
    <a href="{{ url_for('user.validate_secret_key', pecha_id=pecha_id, branch=branch) }}"
        class="btn btn-primary btn-block">Owner</a>
    <a href="{{ url_for('user.register_user', pecha_id=pecha_id, branch=branch, is_owner=False) }}"
        class="btn btn-primary btn-block">Contributor</a>
</form>
{% endblock %}

openpecha-editor-old-master/editor/templates/secret_key_form.html
{% extends "login_layout.html" %}

{% block title %}OpenPecha | Register{% endblock %}

{% block form_content %}
<form method="POST" action="" class="login-form-container">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">{{ title }}</legend>
        <div class="form-group">
            {% if form.secret_key.errors %}
            {{ form.secret_key(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.secret_key.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.secret_key(class="form-control form-control-lg") }}
            {% endif %}
        </div>
    </fieldset>
    <div class="from-group">
        {{ form.submit(class="btn btn-primary btn-block" )}}
    </div>
</form>
{% endblock %}